name: Build and Push Docker image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase image name
        id: prep
        run: echo "::set-output name=image::ghcr.io/${GITHUB_REPOSITORY,,}:latest"

      - name: Build Docker image
        run: docker build -t ${{ steps.prep.outputs.image }} .

      - name: Push Docker image
        run: docker push ${{ steps.prep.outputs.image }}
